[package]
name = "rusty-games"
version = "0.1.0"
edition = "2021"

[dependencies]
noise = "0.8.2"
rand = "0.8.5"
rand_chacha = "0.3.1"
crossterm = "0.27.0"
ratatui = { version = "0.26.1", features = ["crossterm"] }
